=== clarin-eric/fcs-misc/fcs-core-2.0-specs/attachments/DataView-Advanced.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:h="http://www.w3.org/1999/xhtml"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    xml:lang="en" vc:minVersion="1.0" vc:maxVersion="1.1"
    xmlns:adv="http://clarin.eu/fcs/dataview/advanced"
    targetNamespace="http://clarin.eu/fcs/dataview/advanced" elementFormDefault="qualified">

    <xs:annotation>
        <xs:documentation>
            <h:p>
                This schema defines the structure of a
                <h:em>advanced result</h:em> data view.
            </h:p>
            <h:p>
                The value <h:code>application/x-clarin-fcs-adv+xml</h:code>
                MUST be used to indicate a <h:em>generic result</h:em> data view.
            </h:p>
        </xs:documentation>    
    </xs:annotation>

    <xs:element name="Advanced">
        <xs:annotation>
            <xs:documentation>
                <h:p>
                    CLARIN-FCS client MAY
                    normalize white-space and strip leading and tailing
                    white-space and collapse all white-space between
                    tokens to a single #x20 character.
                </h:p>
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <!-- Segements -->
                <xs:element name="Segments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Segment" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>
                                        <h:p>
                                            A segment is ...
                                        </h:p>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:attribute name="id" type="adv:referenceType" use="required">
                                        <xs:annotation>
                                            <xs:documentation>
                                                <h:p>
                                                    A local identifier for this segment. Is used in the &lt;Span&gt; element to refer to a segment.
                                                </h:p>
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="start" type="adv:offsetType" use="required">
                                        <xs:annotation>
                                            <xs:documentation>
                                                <h:p>
                                                    Start offset of the segment.
                                                </h:p>
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="end" type="adv:offsetType" use="required">
                                        <xs:annotation>
                                            <xs:documentation>
                                                <h:p>
                                                    End offset of the segment. The End offset MUST be larger or equal to the start offset.
                                                </h:p>
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="ref" type="xs:anyURI">
                                        <xs:annotation>
                                            <xs:documentation>
                                                <h:p>
                                                    An optional URI supplied by Endpoint which (may be) displayed by Tools like the Aggregator. The Endpoint
                                                    needs to do something useful, if user follows this URI, i.e. display result in own viewer or
                                                    invoke an audio-player, etc.
                                                </h:p>
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="unit" use="required">
                            <xs:annotation>
                                <xs:documentation>
                                    <h:p>
                                        This attribute indicates how the start and end offsets are represented.
                                        They can be either enumerated items, like characters or tokens or timestamps.
                                    </h:p> 
                                </xs:documentation>
                            </xs:annotation>
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="item">
                                        <xs:annotation>
                                            <xs:documentation>
                                                <h:p>
                                                    The start and end offsets represent enumerated items, e.g. like characters or tokens.
                                                </h:p>
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:enumeration>
                                    <xs:enumeration value="timestamp">
                                        <xs:annotation>
                                            <xs:documentation>
                                                <h:p>
                                                    The start and end offsets represent timestamps.
                                                </h:p>
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <!-- Layers-->
                <xs:element name="Layers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Layer" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Span" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="ref" type="adv:referenceType" use="required">
                                                        </xs:attribute>
                                                        <xs:attribute name="highlight" type="adv:highlightType">
                                                            
                                                        </xs:attribute>
                                                        <xs:attribute name="alt-value" type="xs:string">
                                                            
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>                                                
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:anyURI" use="required">
                                    </xs:attribute>
                                </xs:complexType>
                                <xs:unique name="UniqueSegmentRefInSpan">
                                    <xs:selector xpath="adv:Span"/>
                                    <xs:field xpath="@ref"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>                    
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="SegmentId">
            <xs:selector xpath="adv:Segments/adv:Segment"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref refer="adv:SegmentId" name="SegmentRef">
            <xs:selector xpath="adv:Layers/adv:Layer/adv:Span"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
    </xs:element>
    
    <xs:simpleType name="referenceType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z][a-zA-Z0-9]*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="offsetType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+|\d+:([0-5][0-9]|60):([0-5][0-9]|60)\.\d\d\d" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="highlightType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z][a-zA-Z0-9]*" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== clarin-eric/fcs-misc/examples/Core_2/Resource-Advanced-Items.xml
<?xml version="1.0" encoding="UTF-8"?>
<Advanced xmlns="http://clarin.eu/fcs/dataview/advanced"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://clarin.eu/fcs/endpoint-description ../../schema/Core_2/DataView-Advanced.xsd">
    <!-- one can only have one segments part in the dataview, so it's either "characters" or "timestamp" -->
    <!--
           character := Unicode codepoint, normalized to Unicode Normalization Form KC (NFKC; Compatibility
                        Decomposition, followed by Canonical Composition)
                        
         @ref := (optional) uri supplied by endpoint; link (may be) displayed in aggregator; endpoint
                 needs to do something useful, if user follows uri, i.e. display stuff in own viewer,
                 invoke an audio-player, ...
    -->
    <Segments unit="item">
        <Segment id="s1"  start="1"  end="1"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=0:173"/>
        <Segment id="s2"  start="3"  end="4"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=173:304"/>
        <Segment id="s3"  start="6"  end="7"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=173:304"/> 
        <Segment id="s4"  start="9"  end="10"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=304:480"/>
        <Segment id="s5"  start="12" end="16"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=480:1119"/>
        <Segment id="s6"  start="18" end="22"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=1339:1901"/>
        <Segment id="s7"  start="24" end="27"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=1901:2427"/>
        <Segment id="s8"  start="29" end="32"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=3084:3493"/>
        <Segment id="s9"  start="34" end="36"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=3493:3754"/>
        <Segment id="s10" start="38" end="43"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=3754:4274"/> 
    </Segments>
    
    
    <!--
        here a timestamp-typed segments as example
          timestamp "syntax" := H*H:MM:SS.sss
          
          => maximum resolution 1/1000 second
    -->
    <!--
    <Segments unit="timestamp">
        <Segment id="s21" start="00:00:00.000" end="00:00:02.053"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=0:173"/>
        <Segment id="s22" start="00:00:30.000" end="00:10:02.053"
            ref="http://hdl.handle.net/4711/123456789?urlappend=%3Fplay=0:173"/>
    </Segments>
    -->

    <Layers>
        <!-- stacking order for displaying => document order, so first Layer element is top-most in display -->
        
        <Layer id="http://endpoint.example.org/Layers/orth1">
            <Span ref="s1">t</Span>
            <Span ref="s2">da</Span> 
            <Span ref="s3">'s</Span> 
            <Span ref="s4">de</Span> 
            <Span ref="s5">enige</Span> 
            <Span ref="s6">echte</Span> 
            <Span ref="s7">hoop</Span> 
            <Span ref="s8">voor</Span> 
            <Span ref="s9">ons</Span> 
            <Span ref="s10">mensen</Span>
        </Layer>
        
        <Layer id="http://endpoint.example.org/Layers/words1">
            <Span ref="s1" />
            <Span ref="s2" />
            <Span ref="s3" />
            <Span ref="s4" />
            <Span ref="s5" />
            <Span ref="s6" />
            <Span ref="s7" />
            <Span ref="s8" />
            <Span ref="s9" />
            <Span ref="s10" />
        </Layer>
        
        <Layer id="http://endpoint.example.org/Layers/pos1">
            <Span ref="s1"  alt-value="SPEC(afgebr)">X</Span>
            <Span ref="s2"  alt-value="VNW(aanw,pron,stan,vol,3o,ev)">PRON</Span>
            <Span ref="s3"  alt-value="WW(pv,tgw,ev)">VERB</Span>
            <Span ref="s4"  alt-value="LID(bep,stan,rest)">DET</Span>
            <Span ref="s5"  alt-value="VNW(onbep,det,stan,prenom,met-e,rest)">DET</Span>
            <Span ref="s6"  alt-value="ADJ(prenom,basis,met-e,stan)">ADJ</Span>
            <Span ref="s7"  alt-value="N(soort,ev,basis,zijd,stan)">NOUN</Span>
            <Span ref="s8"  alt-value="VZ(init)">ADP</Span>
            <Span ref="s9"  alt-value="VNW(pr,pron,obl,vol,1,mv)">PRON</Span>
            <Span ref="s10" alt-value="N(soort,mv,basis)">NOUN</Span>
        </Layer>
        
        <!-- 
               @highlight := highlight to be put on Span by the endpoint to indicate hits
                             value of highligh is a string; same string == same highlight accent,
                             e.g. Aggregtor could use same color 
        -->
        <Layer id="http://endpoint.example.org/Layers/lemma1">
            <Span ref="s1">_</Span>
            <Span ref="s2">dat</Span>
            <Span ref="s3">zijn</Span>
            <Span ref="s4" >de</Span>
            <Span ref="s5">enig</Span>
            <Span ref="s6" highlight="h1">echt</Span>
            <Span ref="s7" highlight="h1">hoop</Span>
            <Span ref="s8">voor</Span>
            <Span ref="s9">ons</Span>
            <Span ref="s10">mens</Span>
        </Layer>
        
        <!--
            (just example) different @highlight
        -->
        <Layer id="http://endpoint.example.org/Layers/phon">
            <Span ref="s1">t@</Span>
            <Span ref="s2" highlight="h2">dAz</Span>
            <Span ref="s3">dAz</Span>
            <Span ref="s4">d@</Span>
            <Span ref="s5">en@G@</Span>
            <Span ref="s6">Ext@</Span>
            <Span ref="s7">hop</Span>
            <Span ref="s8">for</Span>
            <Span ref="s9">Ons</Span>
            <Span ref="s10">mEns@</Span>
        </Layer>
    </Layers>
</Advanced>
